CREATE TABLE `data_platform_planned_order_component_data`
(
  `PlannedOrder`                            int(16) NOT NULL,
  `PlannedOrderItem`                        int(6) NOT NULL,
  `BillOfMaterial`                          int(16) DEFAULT NULL,
  `BOMItem`                                 int(6) DEFAULT NULL,
  `Operations`                              int(16) DEFAULT NULL,
  `OperationsItem`                          int(6) DEFAULT NULL,
  `Reservation`                             int(16) DEFAULT NULL,
  `ReservationItem`                         int(4) DEFAULT NULL,
  `ComponentProduct`                        varchar(40) DEFAULT NULL,
  `ComponentProductDeliverFromParty`        int(12) DEFAULT NULL,
  `ComponentProductDeliverToParty`          int(12) DEFAULT NULL,
  `ComponentProductBuyer`                   int(12) DEFAULT NULL,
  `ComponentProductSeller`                  int(12) DEFAULT NULL,
  `ComponentProductRequirementDate`         date DEFAULT NULL,
  `ComponentProductRequirementTime`         time DEFAULT NULL,
  `ComponentProductRequiredQuantity`        float(15) DEFAULT NULL,
  `ComponentProductBusinessPartner`         int(12) DEFAULT NULL,
  `BaseUnit`                                varchar(3) DEFAULT NULL,
  `MRPArea`                                 varchar(10) DEFAULT NULL,
  `MRPController`                           varchar(3) DEFAULT NULL,
  `StockConfirmationPartnerFunction`        varchar(40) DEFAULT NULL,
  `StockConfirmationBusinessPartner`        int(12) DEFAULT NULL,
  `StockConfirmationPlant`                  varchar(4) DEFAULT NULL,
  `StockConfirmationPlantBatch`             varchar(10) DEFAULT NULL,
  `StorageLocationForMRP`                   varchar(4) DEFAULT NULL,
  `ComponentWithdrawnQuantity`              float(15) DEFAULT NULL,
  `ComponentScrapInPercent`                 float(7) DEFAULT NULL,
  `OperationScrapInPercent`                 float(7) DEFAULT NULL,
  `QuantityIsFixed`                         tinyint(1) DEFAULT NULL,
  `LastChangeDateTime`                      datetime DEFAULT NULL,
  `IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,
  
  PRIMARY KEY (`PlannedOrder`, `PlannedOrderItem`),

  CONSTRAINT `DataPlatformPlannedOrderComponentData_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BOMItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProduct_fk` FOREIGN KEY (`ComponentProduct`) REFERENCES `data_platform_product_master_general_data` (`Product`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProductDeliverFromParty_fk` FOREIGN KEY (`DeliverFromParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProductDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProductBuyer_fk` FOREIGN KEY (`Buyer`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProductSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataComponentProductBusinessPartner_fk` FOREIGN KEY (`ComponentProductBusinessPartner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`), 
  CONSTRAINT `DataPlatformPlannedOrderComponentDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`), 
  CONSTRAINT `DataPlatformPlannedOrderComponentDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataStockConfirmationPartnerFunction_fk` FOREIGN KEY (`StockConfirmationPartnerFunction`) REFERENCES `data_platform_partner_function_partner_function_data` (`PartnerFunction`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
  CONSTRAINT `DataPlatformPlannedOrderComponentDataStorageLocationForMRP_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StorageLocationForMRP`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`)
  
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
