CREATE TABLE `data_platform_planned_order_header_data`
(
		`PlannedOrder`                            int(16) NOT NULL,
		`PlannedOrderType`                        varchar(4) DEFAULT NULL,
		`Product`                                 varchar(40) DEFAULT NULL,
		`DeliverFromParty`                        int(12) DEFAULT NULL,
		`DeliverToParty`                          int(12) DEFAULT NULL,
		`IssuingPlant`                            varchar(4) DEFAULT NULL,
		`IssuingPlantStorageLocation`             varchar(4) DEFAULT NULL,
		`ReceivingPlant`                          varchar(4) DEFAULT NULL,
		`ReceivingPlantStorageLocation`           varchar(4) DEFAULT NULL,
		`ProductionPlantBusinessPartner`          int(12) DEFAULT NULL,
		`ProductionPlant`                         varchar(4) DEFAULT NULL,
        `ProductionPlantStorageLocation`          varchar(4) DEFAULT NULL,
        `MRPArea`                                 varchar(4) DEFAULT NULL,
        `BaseUnit`                                varchar(3) DEFAULT NULL,
		`PlannedOrderQuantityInBaseUnit`          float(15) DEFAULT NULL,
		`PlannedOrderPlannedScrapQtyInBaseUnit`   float(15) DEFAULT NULL,
		`PlannedOrderIssuingUnit`                 varchar(3) DEFAULT NULL,
		`PlannedOrderReceivingUnit`               varchar(3) DEFAULT NULL,
		`PlannedOrderIssuingQuantity`             float(15) DEFAULT NULL,
		`PlannedOrderReceivingQuantity`           float(15) DEFAULT NULL,
        `PlannedOrderPlannedStartDate`            date DEFAULT NULL,
		`PlannedOrderPlannedStartTime`            time DEFAULT NULL,
		`PlannedOrderPlannedEndDate`              date DEFAULT NULL,
		`PlannedOrderPlannedEndTime`              time DEFAULT NULL,
		`LastChangeDateTime`                      datetime DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`Buyer`                                   int(12) DEFAULT NULL,
		`Seller`                                  int(12) DEFAULT NULL,
		`Project`                                 varchar(24) DEFAULT NULL,
		`Reservation`                             int(16) DEFAULT NULL,
		`PlannedOrderLongText`                    varchar(200) DEFAULT NULL,
		`MRPController`                           varchar(3) DEFAULT NULL,
		`PlannedOrderLongText`                    varchar(200) DEFAULT NULL,
		`PlannedOrderIsFixed`                     tinyint(1) DEFAULT NULL,
		`PlannedOrderBOMFixed`                    tinyint(1) DEFAULT NULL,
		`LastScheduledDate`                       date DEFAULT NULL,
		`ScheduledBasicEndDate`                   date DEFAULT NULL,
		`ScheduledBasicEndTime`                   time DEFAULT NULL,
		`ScheduledBasicStartDate`                 date DEFAULT NULL,
		`ScheduledBasicStartTime`                 time DEFAULT NULL,
		`SchedulingType`                          varchar(1) DEFAULT NULL,

    PRIMARY KEY (`PlannedOrder`),
	
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataIssuingPlant_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataIssuingPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`, `IssuingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
	CONSTRAINT `DataPlatformPlannedOrderHeaderDataReceivingPlant_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataReceivingPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`, `ReceivingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataProductionPlant_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataPlannedOrderIssuingUnit_fk` FOREIGN KEY (`PlannedOrderIssuingUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataPlannedOrderReceivingUnit_fk` FOREIGN KEY (`PlannedOrderReceivingUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataBuyer_fk` FOREIGN KEY (`Buyer`) REFERENCES `data_platform_business_partner_general_data` (`Buyer`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`Buyer`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DataPlatformPlannedOrderHeaderDataReservation_fk` FOREIGN KEY (`Reservation`) REFERENCES `data_platform_reservation_document_header_data` (`Reservation`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
