CREATE TABLE `data_platform_planned_order_item_component_data`
(
  `PlannedOrder`                            int(16) NOT NULL,
  `PlannedOrderItem`                        int(6) NOT NULL,
  `Operations`                              int(16) NOT NULL,
  `OperationsItem`                          int(6) NOT NULL,
  `BillOfMaterial`                          int(16) NOT NULL,
  `BillOfMaterialItem`                      int(6) NOT NULL,
  `ProductionPlantBusinessPartner`          int(12) NOT NULL,
  `ProductionPlant`                         varchar(4) NOT NULL,
  `Reservation`                             int(16) DEFAULT NULL,
  `ReservationItem`                         int(4) DEFAULT NULL,
  `ComponentProduct`                        varchar(40) NOT NULL,
  `ComponentProductDeliverFromParty`        int(12) DEFAULT NULL,
  `ComponentProductDeliverToParty`          int(12) DEFAULT NULL,
  `ComponentProductBuyer`                   int(12) DEFAULT NULL,
  `ComponentProductSeller`                  int(12) DEFAULT NULL,
  `ComponentProductRequirementDate`         date DEFAULT NULL,
  `ComponentProductRequirementTime`         time DEFAULT NULL,
  `ComponentProductRequiredQuantity`        float(15) DEFAULT NULL,
  `BaseUnit`                                varchar(3) NOT NULL,
  `MRPArea`                                 varchar(10) DEFAULT NULL,
  `MRPController`                           varchar(3) DEFAULT NULL,
  `ProductionVersion`                       int(16) DEFAULT NULL,
  `ProductionVersionItem`                   int(6) DEFAULT NULL,
  `StockConfirmationBusinessPartner`        int(12) DEFAULT NULL,
  `StockConfirmationPlant`                  varchar(4) DEFAULT NULL,
  `StockConfirmationPlantStorageLocation`   varchar(4) DEFAULT NULL,
  `ComponentProductBatch`                   varchar(10) DEFAULT NULL,
  `ComponentProductBatchValidityStartDate`  date DEFAULT NULL,
  `ComponentProductBatchValidityStartTime`  time DEFAULT NULL,
  `ComponentProductBatchValidityEndDate`    date DEFAULT NULL,
  `ComponentProductBatchValidityEndTime`    time DEFAULT NULL,
  `ComponentWithdrawnQuantity`              float(15) DEFAULT NULL,
  `ComponentScrapInPercent`                 float(7) DEFAULT NULL,
  `OperationScrapInPercent`                 float(7) DEFAULT NULL,
  `QuantityIsFixed`                         tinyint(1) DEFAULT NULL,
  `CreationDate`	                        date DEFAULT NULL,
  `CreationTime`                            time DEFAULT NULL,
  `LastChangeDate`	                        date DEFAULT NULL,
  `LastChangeTime`                          time DEFAULT NULL,
  `IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,
  
  PRIMARY KEY (`PlannedOrder`, `PlannedOrderItem`, `Operations`, `OperationsItem`, `BillOfMaterial`, `BillOfMaterialItem`),

  CONSTRAINT `DataPlatformPlannedOrderItemComponentData_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataOperations_fk` FOREIGN KEY (`Operations`, `OperationsItem`) REFERENCES `data_platform_operations_item_data` (`Operations`, `OperationsItem`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BOMItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProduct_fk` FOREIGN KEY (`ComponentProduct`) REFERENCES `data_platform_product_master_general_data` (`Product`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProductDeliverFromParty_fk` FOREIGN KEY (`DeliverFromParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProductDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProductBuyer_fk` FOREIGN KEY (`Buyer`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProductSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`Plant`), 
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataStockConfirmationPlantStorageLocation_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataComponentProductBatch_fk` FOREIGN KEY (`ComponentProduct`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `ComponentProductBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
  CONSTRAINT `DataPlatformPlannedOrderItemComponentDataStorageLocationForMRP_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StorageLocationForMRP`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`)
  
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
