CREATE TABLE `data_platform_planned_order_item_component_data`
(
  `PlannedOrder`                                    int(16) NOT NULL,
  `PlannedOrderItem`                                int(6) NOT NULL,
  `BillOfMaterial`                                  int(16) NOT NULL,
  `BillOfMaterialItem`                              int(6) NOT NULL,
  `SupplyChainRelationshipID`                       int(16) NOT NULL,
  `SupplyChainRelationshipDeliveryID`               int(6) NOT NULL,
  `SupplyChainRelationshipDeliveryPlantID`          int(4) NOT NULL,
  `SupplyChainRelationshipStockConfPlantID`         int(4) NOT NULL,
  `ProductionPlantBusinessPartner`                  int(12) NOT NULL,
  `ProductionPlant`                                 varchar(4) NOT NULL,
  `ComponentProduct`                                varchar(40) NOT NULL,
  `ComponentProductBuyer`                           int(12) NOT NULL,
  `ComponentProductSeller`                          int(12) NOT NULL,
  `ComponentProductDeliverToParty`                  int(12) NOT NULL,
  `ComponentProductDeliverToPlant`                  varchar(4) NOT NULL,
  `ComponentProductDeliverFromParty`                int(12) NOT NULL,
  `ComponentProductDeliverFromPlant`                varchar(4) NOT NULL,
  `ComponentProductRequirementDate`                 date NOT NULL,
  `ComponentProductRequirementTime`                 time NOT NULL,
  `ComponentProductPlannedQuantityInBaseUnit`       float(15) NOT NULL,
  `ComponentProductPlannedQuantityInDeliveryUnit`   float(15) NOT NULL,
  `ComponentProductPlannedScrapInPercent`           float(7) DEFAULT NULL,
  `ComponentProductBaseUnit`                        varchar(3) NOT NULL,
  `ComponentProductDeliveryUnit`                    varchar(3) NOT NULL,
  `ComponentProductIsMarkedForBackflush`            tinyint(1) DEFAULT NULL,
  `BillOfMaterialItemText`                          varchar(200) DEFAULT NULL,
  `StockConfirmationBusinessPartner`                int(12) NOT NULL,
  `StockConfirmationPlant`                          varchar(4) NOT NULL,
  `StockConfirmationPlantStorageLocation`           varchar(4) DEFAULT NULL,
  `MRPArea`                                         varchar(10) DEFAULT NULL,
  `MRPController`                                   varchar(3) DEFAULT NULL,
  `ProductionVersion`                               int(16) DEFAULT NULL,
  `ProductionVersionItem`                           int(6) DEFAULT NULL,
  `PlannedOrderIsReleased`                  	    tinyint(1) DEFAULT NULL,
  `CreationDate`	                                date DEFAULT NULL,
  `CreationTime`                                    time DEFAULT NULL,
  `LastChangeDate`	                                date DEFAULT NULL,
  `LastChangeTime`                                  time DEFAULT NULL,
  `IsMarkedForDeletion`                             tinyint(1) DEFAULT NULL,
  
  PRIMARY KEY (`PlannedOrder`, `PlannedOrderItem`, `BillOfMaterial`, `BillOfMaterialItem`),

  CONSTRAINT `DPFMPlannedOrderItemComponentData_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`, `BillOfMaterialItem`) REFERENCES `data_platform_bill_of_material_item_data` (`BillOfMaterial`, `BillOfMaterialItem`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `ComponentProductBuyer`, `ComponentProductSeller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `ComponentProductBuyer`, `ComponentProductSeller`, `ComponentProductDeliverToParty`, `ComponentProductDeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `ComponentProductBuyer`, `ComponentProductSeller`, `ComponentProductDeliverToParty`, `ComponentProductDeliverFromParty`, `ComponentProductDeliverToPlant`, `ComponentProductDeliverFromPlant`, `ComponentProduct`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataSCRStockConfPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `ComponentProductBuyer`, `ComponentProductSeller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `ComponentProduct`) REFERENCES `data_platform_scr_stock_conf_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataComponentProductBaseUnit_fk` FOREIGN KEY (`ComponentProductBaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataComponentProductDeliveryUnit_fk` FOREIGN KEY (`ComponentProductDeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
  CONSTRAINT `DPFMPlannedOrderItemComponentDataStockConfirmationPlantStorageLocation_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`)
  
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
