CREATE TABLE `data_platform_planned_order_item_data`
(
		`PlannedOrder`                            int(16) NOT NULL,
	    `PlannedOrderItem`                        int(6) NOT NULL,
		`Product`                                 varchar(40) DEFAULT NULL,
		`DeliverFromParty`   		              int(12) DEFAULT NULL,
		`DeliverFromPlant`                	  	  varchar(4) DEFAULT NULL,
		`DeliverFromPlantStorageLocation` 		  varchar(4) DEFAULT NULL,
		`DeliverToParty` 		                  int(12) DEFAULT NULL,
		`DeliverToPlant` 		              	  varchar(4) DEFAULT NULL,
		`DeliverToPlantStorageLocation` 	      varchar(4) DEFAULT NULL,
		`ProductionPlantBusinessPartner`          int(12) DEFAULT NULL,
		`ProductionPlant`                         varchar(4) DEFAULT NULL,
        `ProductionPlantStorageLocation`          varchar(4) DEFAULT NULL,
        `BaseUnit`                                varchar(3) DEFAULT NULL,
        `MRPArea`                                 varchar(10) DEFAULT NULL,
		`MRPController`                           varchar(3) DEFAULT NULL,
        `ProductionVersion`                       int(16) DEFAULT NULL,
        `ProductionVersionItem`                   int(6) DEFAULT NULL,
        `BillOfMaterial`                          int(16) DEFAULT NULL,
        `Operations`                              int(16) DEFAULT NULL,
		`PlannedOrderQuantityInBaseUnit`          float(15) DEFAULT NULL,
		`PlannedOrderPlannedScrapQtyInBaseUnit`   float(15) DEFAULT NULL,
		`PlannedOrderIssuingUnit`                 varchar(3) DEFAULT NULL,
		`PlannedOrderReceivingUnit`               varchar(3) DEFAULT NULL,
		`PlannedOrderIssuingQuantity`             float(15) DEFAULT NULL,
		`PlannedOrderReceivingQuantity`           float(15) DEFAULT NULL,
        `PlannedOrderPlannedStartDate`            date DEFAULT NULL,
		`PlannedOrderPlannedStartTime`            time DEFAULT NULL,
		`PlannedOrderPlannedEndDate`              date DEFAULT NULL,
		`PlannedOrderPlannedEndTime`              time DEFAULT NULL,
		`CreationDate`	                          date DEFAULT NULL,
		`CreationTime`                            time DEFAULT NULL,
		`LastChangeDate`	                      date DEFAULT NULL,
		`LastChangeTime`                          time DEFAULT NULL,
		`OrderID`                                 int(16) DEFAULT NULL,
		`OrderItem`                               int(6) DEFAULT NULL,
		`ProductBuyer`                            int(12) DEFAULT NULL,
		`ProductSeller`                           int(12) DEFAULT NULL,
		`Project`                                 varchar(24) DEFAULT NULL,
		`Reservation`                             int(16) DEFAULT NULL,
		`ReservationItem`                         int(4) DEFAULT NULL,
		`PlannedOrderLongText`                    varchar(200) DEFAULT NULL,
		`PlannedOrderIsFixed`                     tinyint(1) DEFAULT NULL,
		`PlannedOrderBOMIsFixed`                  tinyint(1) DEFAULT NULL,
		`LastScheduledDate`                       date DEFAULT NULL,
		`ScheduledBasicEndDate`                   date DEFAULT NULL,
		`ScheduledBasicEndTime`                   time DEFAULT NULL,
		`ScheduledBasicStartDate`                 date DEFAULT NULL,
		`ScheduledBasicStartTime`                 time DEFAULT NULL,
		`SchedulingType`                          varchar(1) DEFAULT NULL,
		`PlannedOrderIsReleased`                  tinyint(1) DEFAULT NULL,
		`IsMarkedForDeletion`                     tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`PlannedOrder`, `PlannedOrderItem`),

    CONSTRAINT `DataPlatformPlannedOrderItemData_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverFromPlant_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverToPlant_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductionPlant_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataOperations_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataStockConfirmationPartnerFunction_fk` FOREIGN KEY (`StockConfirmationPartnerFunction`) REFERENCES `data_platform_partner_function_partner_function_data` (`PartnerFunction`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataStorageLocationForMRP_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StorageLocationForMRP`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataPlannedOrderIssuingUnit_fk` FOREIGN KEY (`PlannedOrderIssuingUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataPlannedOrderReceivingUnit_fk` FOREIGN KEY (`PlannedOrderReceivingUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductBuyer_fk` FOREIGN KEY (`ProductBuyer`) REFERENCES `data_platform_business_partner_general_data` (`Buyer`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductSeller_fk` FOREIGN KEY (`ProductSeller`) REFERENCES `data_platform_business_partner_general_data` (`Buyer`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
