CREATE TABLE `data_platform_planned_order_item_data`
(
		`PlannedOrder`                            	int(16) NOT NULL,
	    `PlannedOrderItem`                        	int(6) NOT NULL,
		`SupplyChainRelationshipID`               	int(16) NOT NULL,
		`SupplyChainRelationshipDeliveryID`         int(6) NOT NULL,
		`SupplyChainRelationshipDeliveryPlantID`    int(4) NOT NULL,
		`SupplyChainRelationshipProductionPlantID`  int(4) DEFAULT NULL,
        `SupplyChainRelationshipStockConfPlantID`   int(4) NOT NULL,
		`PlannedOrderType`                       	varchar(4) NOT NULL,
		`Product`                                 	varchar(40) NOT NULL,
		`Buyer`		                            	int(12) NOT NULL,
		`Seller`    		                       	int(12) NOT NULL,
		`DeliverFromParty`   		              	int(12) NOT NULL,
		`DeliverFromPlant`                	  	  	varchar(4) NOT NULL,
		`DeliverFromPlantStorageLocation` 		  	varchar(4) DEFAULT NULL,
		`DeliverToParty` 		                  	int(12) NOT NULL,
		`DeliverToPlant` 		              	  	varchar(4) NOT NULL,
		`DeliverToPlantStorageLocation` 	      	varchar(4) DEFAULT NULL,
		`ProductionPlantBusinessPartner`          	int(12) DEFAULT NULL,
		`ProductionPlant`                         	varchar(4) DEFAULT NULL,
        `ProductionPlantStorageLocation`          	varchar(4) DEFAULT NULL,
        `BaseUnit`                                	varchar(3) NOT NULL,
        `DeliveryUnit`                            	varchar(3) NOT NULL,
        `MRPArea`                                 	varchar(10) DEFAULT NULL,
		`MRPController`                           	varchar(3) DEFAULT NULL,
        `ProductionVersion`                       	int(16) DEFAULT NULL,
        `ProductionVersionItem`                   	int(6) DEFAULT NULL,
  		`StockConfirmationBusinessPartner`        	int(12) NOT NULL,
  		`StockConfirmationPlant`                  	varchar(4) NOT NULL,
  		`StockConfirmationPlantStorageLocation`   	varchar(4) DEFAULT NULL,
        `BillOfMaterial`                          	int(16) DEFAULT NULL,
        `Operations`                              	int(16) DEFAULT NULL,
		`PlannedOrderQuantityInBaseUnit`          	float(15) DEFAULT NULL,
		`PlannedOrderQuantityInDeliveryUnit`       	float(15) DEFAULT NULL,
		`PlannedOrderQuantityInProductionUnit`     	float(15) DEFAULT NULL,
		`PlannedOrderPlannedScrapQtyInBaseUnit`   	float(15) DEFAULT NULL,
		`PlannedOrderIssuingUnit`                 	varchar(3) DEFAULT NULL,
		`PlannedOrderReceivingUnit`               	varchar(3) DEFAULT NULL,
		`PlannedOrderIssuingQuantity`             	float(15) DEFAULT NULL,
		`PlannedOrderReceivingQuantity`           	float(15) DEFAULT NULL,
        `PlannedOrderPlannedStartDate`            	date DEFAULT NULL,
		`PlannedOrderPlannedStartTime`            	time DEFAULT NULL,
		`PlannedOrderPlannedEndDate`              	date DEFAULT NULL,
		`PlannedOrderPlannedEndTime`              	time DEFAULT NULL,
		`CreationDate`	                          	date DEFAULT NULL,
		`CreationTime`                            	time DEFAULT NULL,
		`LastChangeDate`	                      	date DEFAULT NULL,
		`LastChangeTime`                         	time DEFAULT NULL,
		`OrderID`                                 	int(16) DEFAULT NULL,
		`OrderItem`                               	int(6) DEFAULT NULL,
		`Project`                                 	int(16) DEFAULT NULL,
		`WBSElement`                               	int(8) DEFAULT NULL,
		`Reservation`                             	int(16) DEFAULT NULL,
		`ReservationItem`                         	int(4) DEFAULT NULL,
		`PlannedOrderLongText`                    	varchar(200) DEFAULT NULL,
		`PlannedOrderIsFixed`                     	tinyint(1) DEFAULT NULL,
		`PlannedOrderBOMIsFixed`                  	tinyint(1) DEFAULT NULL,
		`LastScheduledDate`                       	date DEFAULT NULL,
		`ScheduledBasicEndDate`                   	date DEFAULT NULL,
		`ScheduledBasicEndTime`                   	time DEFAULT NULL,
		`ScheduledBasicStartDate`                 	date DEFAULT NULL,
		`ScheduledBasicStartTime`                 	time DEFAULT NULL,
		`SchedulingType`                          	varchar(1) DEFAULT NULL,
		`PlannedOrderIsReleased`                  	tinyint(1) DEFAULT NULL,
		`IsMarkedForDeletion`                     	tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`PlannedOrder`, `PlannedOrderItem`),

    CONSTRAINT `DataPlatformPlannedOrderItemData_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_supply_chain_relationship_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_supply_chain_relationship_delivery_relation_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`, , `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataSCRStockConfPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`) REFERENCES `data_platform_supply_chain_relationship_stock_conf_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipStockConfPlantID`, `Buyer`, `Seller`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `Product`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverFromPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `DeliverFromPlant`, `DeliverFromPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliverToPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `DeliverToPlant`, `DeliverToPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductionPlantStorageLocation_fk` FOREIGN KEY (`ProductionPlantBusinessPartner`, `ProductionPlant`, `ProductionPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProductionVersion_fk` FOREIGN KEY (`ProductionVersion`, `ProductionVersionItem`) REFERENCES `data_platform_production_version_item_data` (`ProductionVersion`, `ProductionVersionItem`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataStockConfirmationPlantStorageLocation_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataBillOfMaterial_fk` FOREIGN KEY (`BillOfMaterial`) REFERENCES `data_platform_bill_of_material_header_data` (`BillOfMaterial`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataOperations_fk` FOREIGN KEY (`Operations`) REFERENCES `data_platform_operations_header_data` (`Operations`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataDeliveryUnit_fk` FOREIGN KEY (`DeliveryUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataOrderItem_fk` FOREIGN KEY (`OrderID`, `OrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DataPlatformPlannedOrderItemDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
	CONSTRAINT `DataPlatformPlannedOrderItemDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
